server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/airbnb_listings_db?createDatabaseIfNotExist=true
    username: root
    password: Uday@4441

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/