server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/airbnb_users_db?createDatabaseIfNotExist=true
    username: root
    password: Uday@4441

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# jwt:
#   secret: POfqiSqzNv8ZQpUzbIxHbtEo5vvjkfK0AYgEd8Lf+9s=
  #gDxFeU51FDBy2JBmrhf9InlNZHGAppXZe1sgFN1g/1o=
  # expiration-ms: 86400000 # 24 hours
